name: FOOD-CI Build and Test

# Controls when the action will run. 
on:
  # Uncomment the 3 lines below and replace with you branch name if you want to test changes to this.
  push:
    branches:
      - 'main'

  pull_request:

jobs:
 
  build:

    name: Build and Test
  
    # The type of runner that the job will run on
    # Using github's runners until we can get docker running on our stuff
    runs-on: ubuntu-latest
    #runs-on: self-hosted

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
            python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          python -m pip install flask
          python -m pip install Flask-Mail

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          pytest unittests.py